---
title: "MLM w/PCA"
author: "Marshae Nickelberry"
date: "2023-12-10"
output: ''
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
library(tidyr)
##install.packages("xts")
library(xts)
##install.packages("lubridate")
library(lubridate)
library(Matrix)


pacman::p_load(readxl, qgraph, corrplot, cluster,factoextra,
              gridExtra,dplyr,scatterplot3d,corrplot,
              stargazer,glmnet,stats,car)
```



```{r}

pm <- read.csv(file_path, header = TRUE, sep = ",", na.strings = c("", "NA"))
hemis<- read.csv("Desktop/HU Y2/Fall 2023/EDU SO43/Final Project/hemisphere.csv", header=TRUE, sep=",", na.strings=c("","NA"))
popdens<- read.csv("Desktop/HU Y2/Fall 2023/EDU SO43/Final Project/pop_density.csv", header=TRUE, sep=",", na.strings=c("","NA"))

```


```{r}
#data cleaning from Jen 
pm <- merge(pm, hemis, by.x = "country", by.y = "Country.Name", all.x = TRUE)
pm <- merge(pm, popdens, by.x = "country", by.y = "Country.Name", all.x = TRUE)
pm <- rename(pm, "pop_density" = "X2020")

```


```{r}
## create a time variable to account for trend
pm$date <- as.Date(pm$date, format = "%Y-%m-%d")
unique_dates <- sort(unique(pm$date))
pm$time_index <- match(pm$date, unique_dates)

## create a month variable to account for seasonality
pm$month <- month(pm$date)
pm$month <- as.factor(pm$month)


#Workplace percent decrease
pm$hdicode <- as.factor(pm$hdicode)
pm <- pm %>%
  mutate(workplaces_reversed = -workplaces_percent_change_from_baseline)

```



```{r}
#look at correlation 

pm2<- na.omit(pm)

cor.matrix <- cor(pm2[, c(6:9, 11, 22)], method = "spearman")
cor.matrix

corrplot(cor.matrix,
         method="number",
         order = "hclust", #clusters recommended to use, to see how to order coefficients. 
         addrect =5,
         #tl.pos = "l" #take this out to be able to read the axis better
         tl.col = "black",
         tl.cex=0.4,
         sig.level = 0.05)
```

#PCA Analysis 

```{r}
#define exposure and outcomee 
X <- as.matrix(pm2[, c(6:9, 11, 22)])
Y<-pm2$a_mean
```


```{r pca}
fit <- prcomp(X, center=TRUE, scale=TRUE)

head(fit$x) #shows PC for all 6 variables 
pc_cor <- cor(fit$x)
print(pc_cor)#off diagonals are close to zero, uncorrelated PCAs 


```
```{r pca_results}
summary(fit)
```
#PC1 explains 90% of the variability, up to PC3 explains 97% of the variability....


```{r}
plot(fit,type="lines") #screeplot
```
Based on screeplot, would choose 2 variables MAX, so interesting.. 


```{r}
rawLoadings_2<- fit$rotation[,1:2]
rawLoadings_2

#rotated loading factors 
rotatedLoadings_2 <- varimax(rawLoadings_2)$loadings
rotatedLoadings_2 #should be full matrix, but they have decided which is important. 
```

```{r}
rawLoadings_3<- fit$rotation[,1:3]
rawLoadings_3

#rotated loading factors 
rotatedLoadings_3 <- varimax(rawLoadings_3)$loadings
rotatedLoadings_3 #should be full matrix, but they have decided which is important. 
```
*side note: negative variabales are negatively correlated, and contribute inversely, any increase in the value of say workplace for PC1, would result in decreae in the the value of PC*


```{r newdata}
pm_PCA <- data.frame(pm2, fit$x)
names(pm_PCA)
```


```{r}
## model 1, 2 PCS
library(lme4)
update.packages(ask = FALSE)
update.packages("Matrix")
library(sjPlot)

pm$hdicode <- factor(relevel(pm$hdicode, ref = "Very High"), levels = c("Low", "Medium", "High", "Very High"))

#x_PC <- glmer(a_mean ~ PC1*hdicode + PC2*hdicode + time_index + month * hemisphere + pop_density + (1 | Mobility_SiteName), 
              #control = glmerControl(optimizer = "bobyqa",
                                      #optCtrl = list(maxfun = 2e5)),  
              #data = pm_PCA)


#summary(x_PC)

x1<- lmer(a_mean ~ PC1*hdicode + PC2*hdicode  + time_index + month*hemisphere + pop_density +
              (1 | Mobility_SiteName), control = lmerControl(optimizer = "bobyqa"),
     data = pm_PCA)

summary(x1)

#Jens model
x <- lmer(a_mean ~ workplaces_reversed*hdicode  + time_index + month*hemisphere + pop_density +
              (1 | Mobility_SiteName), control = lmerControl(optimizer = "bobyqa"),
     data = pm)

summary(x)

#create summary table
model_table <- sjt.lmer(list(x1, x))
```

